# Generated by Django 5.1.3 on 2024-11-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productscrapeevent",
            name="asin",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
